services:
  mysql:
    image: mysql/mysql-server:8.0.30
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      - mysql-data:/var/lib/mysql/
    restart: unless-stopped
    tty: true
    environment:
      - name=value

  app:
    build: .
    container_name: app
    depends_on:
      - mysql
    restart: unless-stopped
    tty: true

  nginx:
    image: nginx:1.25.5-alpine-slim
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/:ro

volumes:
  mysql-data:
    driver: local