services:
  mysql:
    image: mysql/mysql-server:8.0.30
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      - mysql-data:/var/lib/mysql/
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: SUkses@202A

  app:
    build: .
    container_name: app
    depends_on:
      - mysql
    restart: unless-stopped
    tty: true
    ports:
      - 18000:8000

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    ports:
      - 14040:4040
    environment:
      NGROK_AUTHTOKEN: 2T62k8c5RGkGJa0opZas0jJgHP6_5TsWhQdKe6Y7giCvy9Asw
    command: ["http", "http://app:8000"]

volumes:
  mysql-data:
    driver: local